const fs = require('fs');
let code = fs.readFileSync('api/index.ts', 'utf8');

// Replace modelContent checks
code = code.replace(
  'const hasNativeCalls = modelContent && modelContent.parts && modelContent.parts.some((p: any) => p.functionCall);',
  'const hasNativeCalls = aggregatedParts.some((p: any) => p.functionCall);'
);

code = code.replace(
  `          const modelPartsForContents = (hasNativeCalls && modelContent?.parts)
            ? modelContent.parts
            : [
                ...(textForThisTurn ? [{ text: textForThisTurn }] : []),
                // We map functionCallsForThisTurn. Note: If these were auto-injected, Gemini 3.0 might reject them without a thought_signature.
                // But let's restore the original state first.
                ...functionCallsForThisTurn.map(fc => ({ functionCall: fc }))
              ];`,
  `          // For Gemini 3.0, we MUST preserve the exact parts (including thought_signature) generated by the model.
          // If the model generated NO function calls natively, but we auto-injected some, we cannot put them in the model's history as functionCall.
          let modelPartsForContents = aggregatedParts.length > 0 ? aggregatedParts : (textForThisTurn ? [{ text: textForThisTurn }] : [{ text: " " }]);
`
);

// We need to mark auto-injected calls.
code = code.replace(
  `functionCallsForThisTurn.push({ name: fnName, args: fnArgs });`,
  `functionCallsForThisTurn.push({ name: fnName, args: fnArgs, isAutoInjected: true });`
);

code = code.replace(
  `functionCallsForThisTurn.push({ name: "open_url", args: { url: targetUrl } });`,
  `functionCallsForThisTurn.push({ name: "open_url", args: { url: targetUrl }, isAutoInjected: true });`
);

fs.writeFileSync('api/index.ts', code);
